title: Pun Pun's Head Space
author: Pun Pun
email: papattarada1643@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Pun Pun, a Computer Science undergraduate student at the National University of Singapore!
theme: minima

# social links
github_username:  Punpun1643 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
